### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wordandahalf** [TheMCPEGamer/Adventuria#1]
[outdated, will be updated for the slick2d branch]

### World
- [ ] Finish generator; possibly switch to Perlin noise
- [ ] Finish implementing Biomes; possibly add some environmental effects
  - [x] Plains
  - [x] Desert
  - [x] Ocean
  - [ ] Taiga
  - [ ] Forest
  
  (more to come!)
- [ ] Finish Chunk system - dynamically load and render chunks (you must walk to load chunks)
- [ ] Better water physics
- [ ] Finalize level-saving protocol
- [ ] Add block physics
### Entity
- [ ] Add the entitiy tileset into the AssetManager HashMap
- [ ] Fix a load of bugs
- [ ] Add multi-entity support
#### Engine
- [ ] Add particle system
- [ ] Add (proper) walking animation
- [x] OPTIMIZE
- [x] OPTIMIZE
- [ ] OPTIMIZE
- [ ] Finish adding partial variable timing (it gives higher frame rates and fixed tick rates)
- [ ] Finish 60 ticks/second engine
- [ ] Adapt everything to variable timing engine
- [ ] Finish new rendering engine using "Renderer" class
#### GUIs
- [ ] Make a better system (current one is complete rubbish)
- [ ] Fix the Inventory implementation
- [ ] Begin support for block interfaces
### Other
- [ ] Add a multi-language system
- [ ] Add a audio system
  - [ ] Stepping sounds, breaking sounds, etc.
  - [ ] I'll compose some ambient music (similar to Minecraft)
- [x] Make a proper website (Screenshots, pre-compiled binary downloads)
- [ ] Make a multiplayer protocol (Minecraft compatible :trollface:?)
## Bug squashes
- [ ] Collision detection is broken again :(
- [x] Fix stuttering when the player reaches a low X value (must rewrite coordinate system, namely sX and sY in Component.class) - **MIGHT BE FIXED**
- [ ] You can hold items outside your inventory
- [ ] Fix sun/moon stutters at dusk->night and dawn->day transitions

**Comment by MbCrew** [comment]
Hey i was wondering if i could help with this project?

**Comment by MbCrew** [comment]
i just implemented a run feature but for some reason i am no clipling through blocks when i run but not when i walk

**Comment by TheMCPEGamer** [comment]
@MbCrew Could you please commit the changes you made to your fork?

**Comment by redusk** [comment]
@TheMCPEGamer I've fixed the wobbling at low x coordinates.

**Comment by MbCrew** [comment]
cool i will do that

**Comment by TheMCPEGamer** [comment]
Now I need to fix EntityPlayer.isCollidingWithBlock() to use the getBlockX() and getBlockY() methods...

**Comment by redusk** [comment]
I'm changing inventory code. The selected block name is printed in the top center of the screen, and I'll be changing how items are set.

**Comment by TheMCPEGamer** [comment]
@redusk I might add you as a collaborator soon!

**Comment by redusk** [comment]
Sounds good to me. Do you mind if I add stars to the night sky and clouds?

**Comment by TheMCPEGamer** [comment]
@redusk Nope :D

**Comment by redusk** [comment]
Roger dodger

**Comment by TheMCPEGamer** [comment]
@redusk Also, right now, the invBar is being render twice when the inventory is open.

**Comment by redusk** [comment]
I thought something looked strange about that...

**Comment by TheMCPEGamer** [comment]
@redusk Just fixed it

**Comment by TheMCPEGamer** [comment]
Whoops :P

**Comment by redusk** [comment]
I got stars to work, now on to clouds.

**Comment by redusk** [comment]
What is the Debug screen bug?

**Comment by TheMCPEGamer** [comment]
@redusk If you hover an item over the bottom-right cell in the inventory with the Debug screen open, the opacity of the Debug screen text gets screwed up.

I believe all you have to do in order to fix it is to use ```g.setColor(255, 255, 255, 256);``` before drawing the text in Debug.java

**Comment by redusk** [comment]
I'm not getting anything like that, guess we must've accidentally fixed it. I did add a transparent background to the debug menu, maybe that did it?

**Comment by TheMCPEGamer** [comment]
@redusk Yep, just check in Debug.java, and ```g.setColor();``` is used

**Comment by redusk** [comment]
That makes sense.

**Comment by TheMCPEGamer** [comment]
@redusk Are you adding a ```isSolid``` parameter to the BlockID enum?

**Comment by redusk** [comment]
Yup

**Comment by TheMCPEGamer** [comment]
@redusk OK, that's what I would do :-D

**Comment by redusk** [comment]
Do you want to have block mining and placing times?

**Comment by TheMCPEGamer** [comment]
@redusk Just block destroying times.

**Comment by redusk** [comment]
Okay

**Comment by TheMCPEGamer** [comment]
Also, tomorrow, I'm going to start implement level saving, but I may have to rewrite some of the Level code.

**Comment by redusk** [comment]
Sounds good

**Comment by MbCrew** [comment]
i tried to implement block breaking time with a 4 loop based off the blocks hardness but it still just breaks with a click

**Comment by TheMCPEGamer** [comment]
@MbCrew What code are you using?

**Comment by redusk** [comment]
I just got block breaking time implemented. I'll update the codebase in a minute.

**Comment by MbCrew** [comment]
ok cool
i must want to see how you did it

**Comment by MbCrew** [comment]
@TheMCPEGamer im using the code from his i just downloaded the file yesterday and started

**Comment by redusk** [comment]
Use the code from this repository.

**Comment by MbCrew** [comment]
ok got it

**Comment by redusk** [comment]
The block breaking code is in the Level class and Block class.

**Comment by MbCrew** [comment]
ok ill look at it

**Comment by MbCrew** [comment]
i like the way you did that with the textures nice code!!

**Comment by MbCrew** [comment]
ill put up my code for the sprinting in my fork

**Comment by MbCrew** [comment]
ECLIPSE WHY DO YOU FAIL

**Comment by redusk** [comment]
I added a sun and a moon. Now for moon phases!

**Comment by MbCrew** [comment]
I'm getting an error with the isBlockInRange()
it says its undefined for type mouse soooo

**Comment by redusk** [comment]
Press F5 on the project folder in eclipse, your files are out of date.

**Comment by MbCrew** [comment]
ok

**Comment by MbCrew** [comment]
Awesome!!

**Comment by MbCrew** [comment]
were you able to see whats wrong with my sprint?

**Comment by MbCrew** [comment]
i commited in my fork

**Comment by MbCrew** [comment]
im gonna go to bed bya

**Comment by redusk** [comment]
Well, it looks like you are checking to see if you're colliding more than once in a single tick. The canMove boolean should be all you need. Also, you are never setting your new movement speed after seeing if you can run.

**Comment by MbCrew** [comment]
there is a runningSpeed double which is 2 * movementSpeed check

**Comment by redusk** [comment]
Yes, but you aren't using it.

**Comment by MbCrew** [comment]
check keyboardlistener i used it so i could set the players direction when sprinting even though he just points left lol

**Comment by MbCrew** [comment]
by multi entity support do you mean the mobs?

**Comment by MbCrew** [comment]
is anyone on?

**Comment by MbCrew** [comment]
i am working on the Item and ItemID

**Comment by TheMCPEGamer** [comment]
New bug: healthBar & hungerBar render ontop of a held item in the inventory

**Comment by MbCrew** [comment]
what do you mean?

**Comment by redusk** [comment]
I've been heavily rewriting the movement and block detection code, and I've created bounding boxes that entities can use to accurately determine their shapes (more or less).

**Comment by MbCrew** [comment]
im making the break times for blocks which the hardness is divided by the items break time so it will be smaller

**Comment by MbCrew** [comment]
im now about to test it

**Comment by MbCrew** [comment]
where is does it say what item is in the inventory slot? i need to make it Pickaxe

**Comment by MbCrew** [comment]
nvmd

**Comment by MbCrew** [comment]
*SCREAMS* omg i cant make the first item in your inventory an item or it will mess with all the other code and i cant make a block drop the item because I HATE MY LIFE

**Comment by MbCrew** [comment]
im just gonna work on crafting

**Comment by MbCrew** [comment]
you might not here from me for a couple days

**Comment by redusk** [comment]
I've got block detection and player movement working perfectly now. This should make it easier to program other entities too.

**Comment by TheMCPEGamer** [comment]
@redusk I'm not sure if you tested your code, but you can climb up walls like a spider, and you can get stuck by walking into a block

**Comment by TheMCPEGamer** [comment]
Also, is the yellow box around the player for debug purposes?

**Comment by TheMCPEGamer** [comment]
@redusk Also, block breaking is broken

**Comment by redusk** [comment]
Yes, I know about those bugs. I just put the code up so that you could get a basic feel for what's going on. I've fixed most bugs, I'm just working on the falling/jumping code. And the box is for debug purposes. It's the player's bounding box to make collisions more accurate.

**Comment by TheMCPEGamer** [comment]
@redusk I didn't read the commit's comment! Sorry!

**Comment by redusk** [comment]
Okay, I've fixed the spider-man bug.

**Comment by redusk** [comment]
Do we want longer day/night cycles?

**Comment by redusk** [comment]
I think I know what's wrong with your sprint method. Set Component.dir equal to the sprint speed when you press shift. It will move in different directions if the speed is negative or positive.

**Comment by MbCrew** [comment]
coud someone please explain to me how to add things in the inventory class? it is very much confusing

**Comment by MbCrew** [comment]
i need there to be a 2 x 2 but i cant understand how you did it

**Comment by MbCrew** [comment]
i just added a commit it adds tools but i need to wait until i can actually get a tool to make the break times so i have to add crafting

**Comment by TheMCPEGamer** [comment]
I'll add it, soon

**Comment by MbCrew** [comment]
ok im making textures for tools

**Comment by MbCrew** [comment]
i have a hoe and a pick with a hammer end on one side

**Comment by MbCrew** [comment]
I'm doing that because i don't want it to be just like Minecraft i'm also calling the "shovel" a spade

**Comment by MbCrew** [comment]
what do you mean by hold items outside of your inventory?

**Comment by TheMCPEGamer** [comment]
@MbCrew If you select an item in your inventory, you can close your inventory with that item still selected

**Comment by redusk** [comment]
Is the way chunks currently load okay? (see latest commit).

**Comment by TheMCPEGamer** [comment]
I've gotten a basic form of level saving (note: *not* loading) done!

**Comment by redusk** [comment]
Sweet! Should the save files be encrypted so you need a special program to edit them, or are they just plain text?

**Comment by TheMCPEGamer** [comment]
@redusk I'll implement the encryption.

Also, I'm going to start deleting some of the older messages on this thread, as it is getting really long.

**Comment by TheMCPEGamer** [comment]
Just committed level saving, when you hit the 'F' key it saves a file (it always overrides if it already exists) named level.advlevel

**Comment by TheMCPEGamer** [comment]
Right now it is not encrypted, but will be after I add level saving

**Comment by MbCrew** [comment]
goto http://adventuriadev.tk/ 
since i got into web design a while back i figured i'd make a website

**Comment by MbCrew** [comment]
if you have already go on again i changed it a bit 

btw i'm not good at design so give me a background and i will put it up there

**Comment by MbCrew** [comment]
could someone export it to a jar and then send it too my email or dev@adventuriadevtk

**Comment by MbCrew** [comment]
if you do email me i will send you ftp info and the login for the email along with how to

**Comment by MbCrew** [comment]
added a wiki page hope its good

**Comment by redusk** [comment]
We could do a github.io page. It is free and super easy to tell that it's
the right site

**Comment by TheMCPEGamer** [comment]
@redusk I'll make the repository

**Comment by redusk** [comment]
See lurerskape.github.io (my site) and tell me if you want something like
that.

**Comment by MbCrew** [comment]
saw your twitter last tweet was july 25... of last year lol

**Comment by MbCrew** [comment]
im creeped out i got grundink and in the bottom right it says "Hello, Alex(<< my name). I've been expecting you" WTF OMG

**Comment by redusk** [comment]
It's just using whatever your computer username is to generate that sentence. Neat, eh?

**Comment by MbCrew** [comment]
ohh thats so cool

**Comment by MbCrew** [comment]
i like the way your webpage is setup by the way

**Comment by redusk** [comment]
System.getProperty("user.name");

**Comment by MbCrew** [comment]
nice i'm gonna use that someday

**Comment by MbCrew** [comment]
Borderlands is out for IOS

**Comment by TheMCPEGamer** [comment]
@MbCrew Is that the name of your computer?

**Comment by MbCrew** [comment]
Yes Why?

**Comment by MbCrew** [comment]
if you haven't made the repository is it okay if i go ahead and start it?

**Comment by MbCrew** [comment]
what should it be called?

**Comment by TheMCPEGamer** [comment]
@MbCrew I'll create it.

**Comment by TheMCPEGamer** [comment]
@MbCrew Here's the repository: https://github.com/TheMCPEGamer/Adventuria/tree/gh-pages

**Comment by MbCrew** [comment]
is the page up yet? is there anyway i can edit it?

**Comment by redusk** [comment]
The page is at themcpegamer.github.io/Adventuria

**Comment by MbCrew** [comment]
thank you

**Comment by MbCrew** [comment]
is there any way i can help with that?

**Comment by redusk** [comment]
Pull requests?

**Comment by MbCrew** [comment]
ohh sorry i'm kinda new to Github

**Comment by MbCrew** [comment]
it just says there isn't anything to compare

**Comment by redusk** [comment]
Compare across forks

**Comment by MbCrew** [comment]
just did it

**Comment by redusk** [comment]
To save space in level saving, couldn't we have a flag in the chunk class to see if the character has edited it? If the character has placed/removed a block, it will save every block in the chunk to the file. If the chunk hasn't been changed at all, it will save the chunk seed. (What do you think?)

**Comment by redusk** [comment]
To see if the chunk has been changed, you can either get the SHA2 sum of the chunk, or just set Chunk.edited = true when a block is added/removed. (Or something like this)

**Comment by TheMCPEGamer** [comment]
@redusk That'll work.

**Comment by TheMCPEGamer** [comment]
@redusk Maybe we could add vertical chunk loading?
i.e: When you get to a certain y-coordinate, load another chunk below it?

**Comment by redusk** [comment]
Or above it. Spaaaaaace

**Comment by TheMCPEGamer** [comment]
@redusk With a five-chunk-limit upwards and a fifteen-chunk-limit downwards?

**Comment by redusk** [comment]
Sure

**Comment by TheMCPEGamer** [comment]
@redusk Ok

**Comment by TheMCPEGamer** [comment]
@redusk I'll add a Location parameter, and getLocation method to the Chunk class, and CHUNK_MAX_Y and CHUNK_MIN_Y integers.

**Comment by TheMCPEGamer** [comment]
Project revived!
I promise not to abandon it anymore!

Current TODO:
- [ ] Add entities (no AI, for now)
- [ ] Level loading & saving
- [ ] Add vertical chunk loading, possibly redo the chunk system
- [ ] Add an API (using Rhino)
- [ ] Add a pause menu GUI, and change the current system for GUIs

**Comment by TheMCPEGamer** [comment]
Due to numerous issues, I will be rewriting this *entirely* using the LWJGL!

**Comment by redusk** [comment]
Awesome, that's the same library my game uses. I might be able to help with
that!

**Comment by TheMCPEGamer** [comment]
@redusk Should I just use LWJGL 2, since there are more tutorials for it, or is there a greater advantage in using LWJGL 3?

**Comment by TheMCPEGamer** [comment]
I am rewriting it to be 3D and more of a RPG-style game.
However, you will still be able to edit the terrain, just in different ways,

**Comment by TheMCPEGamer** [comment]
Progress so far:

![adventuria_screenshot](https://cloud.githubusercontent.com/assets/10679776/10836892/427410b6-7e81-11e5-83c4-34aef57dd82c.png)

**Comment by redusk** [comment]
That looks nice. What's the render distance?

**Comment by TheMCPEGamer** [comment]
You can do the math ;)

```java
	private static final float NEAR_PLANE = 0.1f;
	private static final float FAR_PLANE = 1500.0f;
```

**Comment by redusk** [comment]
How's the LWJGL progression going?

**Comment by TheMCPEGamer** [comment]
@redusk Pretty good, I'm nearly done with the engine, adding shadow mappings and a skybox.

**Comment by redusk** [comment]
@TheMCPEGamer awesome!

**Comment by redusk** [comment]
You wouldn't mind me continuing the 2D version and building on that would you (maybe a separate branch or fork)? We have done quite a bit with it

**Comment by redusk** [comment]
And I'd love to help with the 3D version too, if you'd like

**Comment by TheMCPEGamer** [comment]
@redusk I have the 3D engine done (for the most part), but I really don't have anything to do with it (ideas would be appreciated)

In the meantime, I have started to rewriting the vast majority of the 2D version, as I have learned a lot and have realized how completely atrocious the code is.

Current TODO for Rewrite:
### Rendering/Textures
[] Redo system to use aliases for textures (**done** for the blocks)
[] Make rendering system more efficient
### World
[] Redo world system to automatically load chunks
### Entities
[] idek what the heck I did, so rewrite all da things
### Codebase
[] Make code more manageable, it's a pain to fix right now

**Comment by TheMCPEGamer** [comment]
An example for the texture aliases:
```java
//Instead of:
g.drawImage(AssetManager.tileset_terrrain, x, y, blah blah blah, null);
//Use:
g.drawImage(AssetManager.getTexture("dirt"), x, y, null); //Where AssetManager.getTexture("dirt") is the texture for the dirt block
```

**Comment by TheMCPEGamer** [comment]
Cleaned the comments up a little bit

**Comment by TheMCPEGamer** [comment]
Today I've rewritten nearly all of the level code, added biomes, added the possibility for different world generators, and best of all, made the rendering engine 1000% more efficient (but introduced a bug)

**Comment by TheMCPEGamer** [comment]
**TODO ASAP**:
Rewrite the atrocity that is the EntityPlayer class, there is no reason for there to be a bajilion different constants

**Comment by redusk** [comment]
Block breaking is non-existent and I keep falling off of the world, but it runs better!

**Comment by TheMCPEGamer** [comment]
@redusk I'll fix block placing and breaking now :)

**Comment by TheMCPEGamer** [comment]
Block breaking is fixed!

**Comment by TheMCPEGamer** [comment]
Working on some better water physics now!

**Comment by redusk** [comment]
I'm working on falling block physics.

**Comment by redusk** [comment]
I'm also changing the rendering engine to get the max FPS possible, but still have physics run at the same speed using deltas.

**Comment by redusk** [comment]
After that, I will work on adding vector based physics and rewriting entites.

**Comment by TheMCPEGamer** [comment]
I'm working on a rewrite to reorganize and fix some of the sloppy code that I wrote.
It *might* be done soon, no promises though

**Comment by wordandahalf** [comment]
Also, in the rewrite, there will be a new way to add textures into the game;
In the `res` folder there will be a file named `assets.dat` with a list of textures the game needs to run, which are parsed on boot.

An example file:

``` php
#The format for adding new textures is:
#alias {image, x1, y1, width, height}
#or just
#alias {image}
dirt {tileset_terrain.png, 0, 0, 20, 20}
stone {tileset_terrain.png, 20, 0, 20, 20}
sky_moon {moon.png}
```

**Comment by redusk** [comment]
I fixed Sun and moon stutters and made their motion more realistic

**Comment by DatCodeDoe** [comment]
I added a working sprint with the shift key

**Comment by DatCodeDoe** [comment]
I made an exe for windows and it works I can also make one for mac and Linux if you want...

**Comment by DatCodeDoe** [comment]
I made a website with some download links, it's pretty basic for now but I will add more info soon
Adventuria.tk

**Comment by DatCodeDoe** [comment]
Added a screenie...

**Comment by TheMCPEGamer** [comment]
![screenshot from 2016-06-11 15-48-41](https://cloud.githubusercontent.com/assets/10679776/15987403/c1f6087c-2fec-11e6-94fc-5386142cd76a.png)

I guess there's some progress :P

**Comment by TheMCPEGamer** [comment]
![screenshot from 2016-06-11 17-31-56](https://cloud.githubusercontent.com/assets/10679776/15987752/6d9f31a0-2ffa-11e6-91f8-4635e661264a.png)

Getting there...

I have no clue why the blocks are rendered so small :P

**Comment by TheMCPEGamer** [comment]
![screenshot from 2016-06-11 21-15-08](https://cloud.githubusercontent.com/assets/10679776/15988522/a39bd596-3019-11e6-8d42-513ed7cd3a29.png)
Getting somewhere :)

**Comment by TheMCPEGamer** [comment]
![screenshot from 2016-06-13 14-48-16](https://cloud.githubusercontent.com/assets/10679776/16020965/e5145306-3175-11e6-948b-a9208a05d2ee.png)
Now I just need to fix frustum culling, and then I should be good :D

**Comment by wordandahalf** [comment]
Fixed a stupid math mistake and now all is good!
![progress_screenshot](https://cloud.githubusercontent.com/assets/10679776/16430773/f6847e80-3d42-11e6-8f9c-a9844ae0a035.png)

**Comment by wordandahalf** [comment]
Working on collision and a new physics engine :)
![progress_screenshot_2](https://cloud.githubusercontent.com/assets/10679776/16432081/34637a20-3d49-11e6-969e-886ecc2f73b6.png)

(I'm also cleaning up this thread)

**Comment by wordandahalf** [comment]
I would like to inform you guys that this is certainly not dead
After rewriting most of the systems, the performance was quite abysmal, even after I optimized it as much as I could. As a result, I am rewriting it in C++ with SDL2. It will be pushed to a new repository within the month.

**Comment by redusk** [comment]
I've been a bit bored lately and have just been toying around with the latest commited version,
and I fixed collision detection and began to add world generation (ore, stone, bedrock, etc.)

**Comment by redusk** [comment]
![lighting](https://cloud.githubusercontent.com/assets/8083367/25625911/0c725382-2f1b-11e7-9d95-bab68c8b2392.PNG)
I've added a rudimentary lighting system

**Comment by wordandahalf** [comment]
Nice!

**Comment by wordandahalf** [comment]
(using the GitHub "Projects" feature instead of this in the future)
